name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t gokai30/quiz8:v0.1 .

      - name: Run tests inside Docker
        run: docker run --rm gokai30/quiz8:v0.1 pytest